language: node_js
node_js:
- '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
addons:
  sauce_connect: true
env:
  global:
  - secure: Db/pckKu1NfS3pmk16esaZDKzbdIdhKjrt2f2ckQjPfxcAdsgvlR9l+s6RtBJr39Iatb6kdDWVS9RriASxXIi/IgOnfyuWNw5xLlUncuudMk2U8+pRmTPhwesl/lF2POxExUXWCPpG6+Muq917eRbjtlgH4tnk3UCwJE92AAjs4=
  - secure: BMobdElHj8aO+7qxfgN7AIG7SFKgYETHzSEkjmIW0s2Q8Ul3d+lROHqKk+x1TN/YtDDcapHImutzrv9vILxjTucHmYgCVAL/z0oBPnlXAz0C5aNwJzNDoNTFuBKw8nF7GgRO7C/kvGLbCTGOG31HQr6MIxTbvy07kUc1kar1VE8=
  - secure: gjBepjzk4rFu6Uq48xuZprZ6cBrpqW6W7Og9uqv71xeMN9HhGhVcqWxQfnP10ZxNt7/JN1bX4Uo/3RU4FqK1azSPQ8kmxgsgqsJdaMUdk6f+1V5iFLTWU9a6kMlUqPbrn4qRNOSue+peLAJ5z9MORmi4A5d/JFbY/h2e+oWZOaM=
